# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://burhaninho.github.io/
baseurl: /
title: Mohamed Burhan
author: Mohamed Burhan
description: Personal blog and resume
avatar: https://raw.githubusercontent.com/burhaninho/burhaninho.github.io/master/images/bio-photo.jpg
email: me@burhaninho.com
github: burhaninho
twitter: burhaninho
linkedin: burhaninho
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
