---
title: Mohamed Burhan | A Doctor Based in Kismayo, Somalia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: "/:title.html"
paginate: 5
gems:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
port: 3000
safe: true
url: http://burhaninho.com
baseurl: http://burhaninho.com/
author: burhaninho
description: Mohamed Burhan - A Father, Doctor, Lecturer and Entrepreneur based in Kismayo, Jubbaland, Somalia.
avatar: bio.png
twitter:
  username: burhaninho
social:
  name: burhaninho
  links:
    - https://twitter.com/burhaninho
    - https://www.facebook.com/burhaninho
    - https://www.linkedin.com/in/burhaninho
    - https://github.com/burhaninho
email: me@burhaninho.com
github: burhaninho
twitter: burhaninho
linkedin: burhaninho
google_analytics: UA-69391421-1
exclude:
- vendor
